name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Inject slug/short variables # so that we can reference $GITHUB_HEAD_REF_SLUG for branch name
      uses: rlespinasse/github-slug-action@v3.x
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # Install node 12 for running maven-semantic-release.
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install maven-semantic-release
      # FIXME: Enable cache for node packages (add package.json?)
      run: |
        yarn global add @conveyal/maven-semantic-release semantic-release
        # Add yarn path to GITHUB_PATH so that global package is executable.
        echo "$(yarn global bin)" >> $GITHUB_PATH
    - name: Setup Maven Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.m2
        key: maven-local-repo
    - name: Build with Maven
      run: mvn --no-transfer-progress package
    - name: Codecov
      # this first codecov run will upload a report associated with the commit set through CI environment variables
      uses: codecov/codecov-action@v1.2.0
      continue-on-error: true
    - name: Clear contents of the target directory
      # Avoids issues where maven-semantic-release attempts to upload
      # multiple versions/builds (and fails due to the pre-existence of the version on maven central).
      run: rm -rf target/*
          # run maven-semantic-release to potentially create a new release of gtfs-lib.
          #
          # If maven-semantic-release finishes successfully and the current branch is master, upload coverage reports for the
          # commits that maven-semantic-release generated. Since the above codecov run is associated with the commit that
          # initiated the Travis build, the report will not be associated with the commits that maven-semantic-release performed
          # (if it ended up creating a release and the two commits that were a part of that workflow). Therefore, if on master
          # codecov needs to be ran two more times to create codecov reports for the commits made by maven-semantic-release.
          # See https://github.com/conveyal/gtfs-lib/issues/193.
          #
      # The git commands get the commit hash of the HEAD commit and the commit just before HEAD.
    - name: Run maven-semantic-release
      run: |
       semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --dev-branch=dev --skip-maven-deploy
       if [[ "$GITHUB_REF_SLUG" = "master" ]]; then
         bash <(curl -s https://codecov.io/bash) -C "$(git rev-parse HEAD)"
         bash <(curl -s https://codecov.io/bash) -C "$(git rev-parse HEAD^)"
       fi
